// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed 4 million, find the sum of the even-valued terms.

const maxVal = 4000000; // If a new fib number is bigger than this it will stop
let numbers = [1,2]; //priming the pump...

let lastNumber; //This will refer to the last number in the array
let secondToLastNumber; //And this to the second to last
let newNumber; // This will be the sum of the two, aka the new fib number

let run = true; //Our while loop will eventually break when the array is full

while(run){
  lastNumber = numbers[numbers.length-1]; //just finds the last number
  secondToLastNumber = numbers[numbers.length-2] //finds the second to last
  newNumber = lastNumber + secondToLastNumber; //determines what the new number will be
  if (newNumber < maxVal){ //If the new number is smaller than the max allowable...
    numbers.push(newNumber); //it adds it to eh array
  }

  else{
    run = false; //as soon as we get a new fib# bigger than 4*10^6 we quit
  }

}

function justEvens(array){ //This splices out all odd numbers in an array
  let x = 0; //starting the iteration
  while (x < array.length){ //this will run through the whole array...
    if (array[x]%2 != 0){ //If the element in question is odd...
      array.splice(x,1); //it kicks it out
    }
    else {x += 1}; //otherwise it looks to the next element and we start over
  }
  return array //the function's output is the amended, evens-only array
}

function arraySum(array){ //adds up all the elements in an array
  let x = 0; //start the iteration
  let sum = 0; //start the sum at 0
  while (x < array.length){ //loop through every element
    sum += array[x]; //adding each one to the total sum
    x+=1; //then moving onto the next element
  }
  return sum; //afterward, return the total
}

console.log(arraySum(justEvens(numbers))); //this prints out the sum of an array filled with the even fibonnaci numbers less than 4 million
